import type { Certificate } from '../models/Certificate.model';
import { parsePermissions } from './crypto.utils';

export interface ReadmeTemplateData {
  certificate: Certificate;
  host?: string;
  port?: number;
  username: string;
  privateKeyPath: string;
  instructions: string;
}

export function generateReadmeMarkdown(data: ReadmeTemplateData): string {
  const { certificate, host, port = 22, username, privateKeyPath, instructions } = data;
  const permissions = parsePermissions(certificate.permissions);
  const expiresAt = new Date(certificate.expires_at).toLocaleString();

  return `# SSH/SFTP Certificate Access

## Certificate Details

- **Certificate ID**: \`${certificate.id}\`
- **Username**: \`${username}\`
- **Host**: \`${host || '<your-server-ip>'}\`
- **Port**: \`${port}\`
- **Directory**: \`${certificate.directory_path}\`
- **Permissions**: ${permissions.join(', ')}
- **Expires**: ${expiresAt}
- **Status**: ${certificate.status}

---

## Quick Start

### SFTP Connection

\`\`\`bash
sftp -i ${privateKeyPath} ${username}@${host || '<your-server-ip>'}
\`\`\`

### SSH Connection (if SSH permission is granted)

\`\`\`bash
ssh -i ${privateKeyPath} ${username}@${host || '<your-server-ip>'}
\`\`\`

### Using FileZilla or other GUI clients

1. Open FileZilla or your preferred SFTP client
2. Host: \`${host || '<your-server-ip>'}\`
3. Port: \`${port}\`
4. Protocol: SFTP
5. User: \`${username}\`
6. Key file: Select the downloaded private key file

---

## Important Notes

### Security
- **Keep your private key safe!** Anyone with access to this key can connect to the server.
- This private key is stored with restrictive permissions (600) on the server.
- Download this key and store it securely.
- Never share this key or commit it to version control.

### Access Limitations
- You are **chrooted** to \`${certificate.directory_path}\`
- You can only access files within this directory
- The certificate will automatically **expire** on: ${expiresAt}

### Permissions Explained
${generatePermissionDescriptions(permissions)}

---

## Troubleshooting

### Permission Denied
\`\`\`bash
# Fix private key permissions
chmod 600 ${privateKeyPath}
\`\`\`

### Connection Refused
- Verify the server IP is correct
- Check that the SSH service is running
- Ensure the certificate has not expired
- Verify your firewall allows connections on port ${port}

### Debug Mode
\`\`\`bash
# Enable verbose output for debugging
sftp -v -i ${privateKeyPath} ${username}@${host || '<your-server-ip>'}
\`\`\`

---

## Configuration Commands

### Set Host Variable (optional)
\`\`\`bash
export VM_HOST="${host || '<your-server-ip>'}"
\`\`\`

### One-line Connection
\`\`\`bash
sftp -i ${privateKeyPath} ${username}@${host || '<your-server-ip>'}
\`\`\`

---

## Additional Instructions

${instructions}

---

*Generated by VM Access API*
*This certificate is temporary and will be automatically revoked upon expiration.*
`;
}

function generatePermissionDescriptions(permissions: string[]): string {
  const descriptions: string[] = [];

  if (permissions.includes('sftp')) {
    descriptions.push('- **SFTP**: You can upload, download, and manage files via SFTP');
  }

  if (permissions.includes('ssh')) {
    descriptions.push('- **SSH**: You have shell access for command-line operations');
  }

  if (permissions.includes('read-only')) {
    descriptions.push('- **Read-Only**: You can only download/view files, not modify them');
  }

  if (permissions.includes('read-write')) {
    descriptions.push('- **Read-Write**: You can create, modify, and delete files');
  }

  return descriptions.join('\n') || '- No special permissions specified';
}

export function formatReadmeAsHtml(markdown: string): string {
  // Simple markdown to HTML conversion
  return markdown
    .replace(/^### (.*$)/gim, '<h3>$1</h3>')
    .replace(/^## (.*$)/gim, '<h2>$1</h2>')
    .replace(/^# (.*$)/gim, '<h1>$1</h1>')
    .replace(/\*\*(.*?)\*\*/gim, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/gim, '<em>$1</em>')
    .replace(/`(.*?)`/gim, '<code>$1</code>')
    .replace(/```bash\n([\s\S]*?)```/gim, '<pre><code class="bash">$1</code></pre>')
    .replace(/```([\s\S]*?)```/gim, '<pre><code>$1</code></pre>')
    .replace(/^- (.*$)/gim, '<li>$1</li>')
    .replace(/\n/gim, '<br>');
}

export function getDownloadInstructions(certificateId: string): string {
  return `
### Download Links

You can download your credentials using these API endpoints:

1. **Private Key**:
   \`\`\`bash
   curl -X GET http://your-api-host/api/download/${certificateId}/key \\
     -H "Authorization: Bearer YOUR_TOKEN" \\
     -o private_key
   \`\`\`

2. **README** (this file):
   \`\`\`bash
   curl -X GET http://your-api-host/api/download/${certificateId}/readme \\
     -H "Authorization: Bearer YOUR_TOKEN" \\
     -o README.md
   \`\`\`

3. **README as JSON**:
   \`\`\`bash
   curl -X GET http://your-api-host/api/download/${certificateId}/content \\
     -H "Authorization: Bearer YOUR_TOKEN"
   \`\`\`
`;
}
